import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect} from 'react'
//import Heart from "../components/Heart"

import styles from '../styles/Home.module.css'

export default function Home() {
  const [frame, setFrame] = useState(0)
  const [fps, setFPS] = useState(20)
  const maxFrame = 200

  useEffect(() => {
    const interval = setInterval(() => {
      setFrame(frame => (frame<maxFrame)? frame+1 : 0)
    }, 1000/fps)
    return () => clearInterval(interval)
  },[])

  return (
    <main className={styles.main}>
      <Head>
         <title>Feliz dia dos namorados Giulia!</title>
         <meta name="description" content="Feliz dia dos namorados Giulia!" />
         <link rel="icon" href="/favicon.svg" />
         <script
          id="MathJax-script"
          async
          src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
        ></script>
      </Head>
      <Image src={'/giulia.svg'} width={450} height={200}/>
      <Image src={'/equation.svg'} width={450} height={40}/>
      <div className={styles.love__wrapper}>
        <Image src={'/I.svg'} width={80} height={200}/>
        <div className='heartAnimation__wrapper'>
          <div className='heartAnimation'></div>
        </div>
        <Image src={'/U.svg'} width={100} height={200}/>
      </div>
      <div className={styles.photo__wrapper}>
        <Image src={'/photo.jpg'} width={400} height={400}/>
      </div>
      <h1>Feliz dia dos namorados!</h1>
    </main>
  )
}
  
//   (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
